# Generated by Django 6.0.4 on 2026-04-21 05:53

import django.db.models.deletion
import files.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to=files.models.encrypted_upload_path)),
                ('content_type', models.CharField(max_length=120)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('ephemeral_public_key', models.TextField()),
                ('nonce_hex', models.CharField(max_length=64)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encrypted_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
