# Generated by Django 6.0.4 on 2026-04-24 12:58

import files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encryptedfile',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Encrypted File', 'verbose_name_plural': 'Encrypted Files'},
        ),
        migrations.RemoveField(
            model_name='encryptedfile',
            name='nonce_hex',
        ),
        migrations.AddField(
            model_name='encryptedfile',
            name='nonce',
            field=models.CharField(default='', help_text='AES-GCM nonce (hex encoded)', max_length=64),
        ),
        migrations.AlterField(
            model_name='encryptedfile',
            name='content_type',
            field=models.CharField(help_text='MIME type of the original file', max_length=120),
        ),
        migrations.AlterField(
            model_name='encryptedfile',
            name='ephemeral_public_key',
            field=models.TextField(help_text='Ephemeral ECC public key (PEM format)'),
        ),
        migrations.AlterField(
            model_name='encryptedfile',
            name='file',
            field=models.FileField(help_text='Encrypted file content', upload_to=files.models.encrypted_upload_path),
        ),
        migrations.AlterField(
            model_name='encryptedfile',
            name='original_filename',
            field=models.CharField(help_text='Original filename before encryption', max_length=255),
        ),
    ]
